<a href="https://colab.research.google.com/github/Moquiuti/python-inteligencia-artificial-aplicada/blob/main/arquivos_e_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Lista de e-mails de exemplo

emails = [
    "Olá equipe, precisamos revisar o cronograma do projeto e validar os prazos com o fornecedor.",
    "Cliente relatou dificuldade no acesso ao portal após redefinir a senha.",
    "Concluímos a reunião de alinhamento e vamos priorizar as integrações críticas até sexta-feira."
]

In [2]:
# Função para gerar resumos simples sem LLM, apenas para praticar lista, append e f-string

def gerar_resumos(lista_emails):
    lista_de_resumos = []

    for indice, email in enumerate(lista_emails, start=1):
        resumo = f"E-mail {indice}: {email[:60]}..."
        lista_de_resumos.append(resumo)

    return lista_de_resumos

In [3]:
resumos = gerar_resumos(emails)

for item in resumos:
    print(item)

E-mail 1: Olá equipe, precisamos revisar o cronograma do projeto e val...
E-mail 2: Cliente relatou dificuldade no acesso ao portal após redefin...
E-mail 3: Concluímos a reunião de alinhamento e vamos priorizar as int...

In [4]:
# Salvando os resumos em arquivo txt

with open("resumos_emails.txt", "w", encoding="utf-8") as arquivo:
    for resumo in resumos:
        arquivo.write(resumo + "\n")

In [5]:
# Lendo linha por linha e salvando em nova lista, removendo quebra de linha

linhas_lidas = []

with open("resumos_emails.txt", "r", encoding="utf-8") as arquivo:
    for linha in arquivo:
        linhas_lidas.append(linha.strip())

linhas_lidas

['E-mail 1: Olá equipe, precisamos revisar o cronograma do projeto e val...',
 'E-mail 2: Cliente relatou dificuldade no acesso ao portal após redefin...',
 'E-mail 3: Concluímos a reunião de alinhamento e vamos priorizar as int...']

In [6]:
# read() -> lê tudo de uma vez

with open("resumos_emails.txt", "r", encoding="utf-8") as arquivo:
    conteudo_completo = arquivo.read()

print("Usando read():\n")
print(conteudo_completo)

Usando read():

E-mail 1: Olá equipe, precisamos revisar o cronograma do projeto e val...
E-mail 2: Cliente relatou dificuldade no acesso ao portal após redefin...
E-mail 3: Concluímos a reunião de alinhamento e vamos priorizar as int...

In [7]:
# readline() -> lê uma linha por vez

with open("resumos_emails.txt", "r", encoding="utf-8") as arquivo:
    primeira_linha = arquivo.readline().strip()
    segunda_linha = arquivo.readline().strip()

print("Primeira linha:", primeira_linha)
print("Segunda linha:", segunda_linha)

Primeira linha: E-mail 1: Olá equipe, precisamos revisar o cronograma do projeto e val...
Segunda linha: E-mail 2: Cliente relatou dificuldade no acesso ao portal após redefin...

In [8]:
# readlines() -> devolve lista de linhas

with open("resumos_emails.txt", "r", encoding="utf-8") as arquivo:
    todas_as_linhas = arquivo.readlines()

print(todas_as_linhas)

['E-mail 1: Olá equipe, precisamos revisar o cronograma do projeto e val...\n', 'E-mail 2: Cliente relatou dificuldade no acesso ao portal após redefin...\n', 'E-mail 3: Concluímos a reunião de alinhamento e vamos priorizar as int...\n']

In [9]:
# Limpando as quebras de linha vindas do readlines()

linhas_tratadas = [linha.strip() for linha in todas_as_linhas]
print(linhas_tratadas)

['E-mail 1: Olá equipe, precisamos revisar o cronograma do projeto e val...', 'E-mail 2: Cliente relatou dificuldade no acesso ao portal após redefin...', 'E-mail 3: Concluímos a reunião de alinhamento e vamos priorizar as int...']

In [10]:
import pandas as pd

In [11]:
# Lista de dicionários com nome e média

alunos = [
    {"nome": "Ana", "media": 7.5},
    {"nome": "Carlos", "media": 8.2},
    {"nome": "Beatriz", "media": 9.1},
    {"nome": "Diogo", "media": 6.8}
]

In [12]:
# Criando arquivo CSV manualmente com vírgula

with open("alunos_manual.csv", "w", encoding="utf-8") as arquivo:
    arquivo.write("nome,media\n")

    for aluno in alunos:
        arquivo.write(f"{aluno['nome']},{aluno['media']}\n")

In [13]:
df_alunos = pd.DataFrame(alunos)
df_alunos

      nome  media
0      Ana    7.5
1   Carlos    8.2
2  Beatriz    9.1
3    Diogo    6.8

In [14]:
df_alunos.to_csv("alunos_pandas.csv", index=False, encoding="utf-8")
print("CSV salvo com sucesso.")

CSV salvo com sucesso.

In [15]:
df_lido = pd.read_csv("alunos_pandas.csv")
df_lido

      nome  media
0      Ana    7.5
1   Carlos    8.2
2  Beatriz    9.1
3    Diogo    6.8

In [16]:
print(df_lido.head())

      nome  media
0      Ana    7.5
1   Carlos    8.2
2  Beatriz    9.1
3    Diogo    6.8

In [17]:
print(df_lido.tail())

      nome  media
0      Ana    7.5
1   Carlos    8.2
2  Beatriz    9.1
3    Diogo    6.8

In [18]:
df_meu_csv = pd.read_csv("meu_csv.csv")
df_meu_csv

       nome  media
0       Ana    7.5
1    Carlos    8.2
2   Beatriz    9.1
3     Diogo    6.8
4   Eduarda    5.9
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

In [19]:
df_alunos.to_csv("alunos_excel.csv", index=False, encoding="utf-8", sep=";")
print("Arquivo com ponto e vírgula gerado.")

Arquivo com ponto e vírgula gerado.

In [20]:
perguntas = [
    "O que é inteligência artificial?",
    "O que é um DataFrame no pandas?",
    "Qual a diferença entre read e readlines em Python?",
    "Para que serve um arquivo CSV?"
]

In [21]:
with open("perguntas.txt", "w", encoding="utf-8") as arquivo:
    for pergunta in perguntas:
        arquivo.write(pergunta + "\n")

In [22]:
lista_perguntas_lidas = []

with open("perguntas.txt", "r", encoding="utf-8") as arquivo:
    for linha in arquivo:
        lista_perguntas_lidas.append(linha.strip())

lista_perguntas_lidas

['O que é inteligência artificial?',
 'O que é um DataFrame no pandas?',
 'Qual a diferença entre read e readlines em Python?',
 'Para que serve um arquivo CSV?']

In [23]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.7/141.7 kB 9.2 MB/s eta 0:00:00

In [25]:
import os
from google.colab import userdata
from groq import Groq

os.environ["GROQ_API_KEY"] = userdata.get("CursoAluraPytonIaGenerative")
client_groq = Groq()

print("Cliente Groq configurado com sucesso.")

Cliente Groq configurado com sucesso.

In [26]:
def responder_pergunta(pergunta):
    resposta = client_groq.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "system",
                "content": (
                    "Responda em português de forma curta, clara e objetiva, em no máximo 2 frases."
                )
            },
            {
                "role": "user",
                "content": pergunta
            }
        ],
        temperature=0.2,
        reasoning_effort="low",
        max_completion_tokens=300
    )

    conteudo = resposta.choices[0].message.content

    if conteudo is None:
        return "Resposta não retornada pela API."

    conteudo = conteudo.strip()

    if conteudo == "":
        return "Resposta veio vazia."

    return conteudo

In [27]:
resultado_final = []

for pergunta in lista_perguntas_lidas:
    resposta = responder_pergunta(pergunta)

    resultado_final.append({
        "pergunta": pergunta,
        "resposta": resposta
    })

resultado_final

[{'pergunta': 'O que é inteligência artificial?',
  'resposta': 'Inteligência artificial é a capacidade de máquinas de executar tarefas que normalmente requerem inteligência humana, como aprendizado, raciocínio e tomada de decisão. Ela utiliza algoritmos e dados para reconhecer padrões, melhorar seu desempenho e adaptar-se a novas situações.'},
 {'pergunta': 'O que é um DataFrame no pandas?',
  'resposta': 'Um DataFrame é uma estrutura de dados bidimensional do pandas que armazena dados em colunas nomeadas, semelhante a uma tabela de banco de dados ou planilha. Ele permite manipulação, filtragem e análise eficiente de grandes volumes de dados.'},
 {'pergunta': 'Qual a diferença entre read e readlines em Python?',
  'resposta': '`read()` lê todo o conteúdo do arquivo de uma vez e devolve uma única string.  \n`readlines()` lê linha por linha, retornando uma lista onde cada elemento é uma linha.'},
 {'pergunta': 'Para que serve um arquivo CSV?',
  'resposta': 'Um arquivo CSV (Comma-Separated Values) armazena dados tabulares em formato de texto, onde cada linha representa um registro e cada campo é separado por vírgula (ou outro delimitador). Ele facilita a troca e importação de dados entre diferentes programas, como planilhas e bancos de dados.'}]

In [28]:
df_resultado = pd.DataFrame(resultado_final)
df_resultado

,pergunta,resposta
0,O que é inteligência artificial?,Inteligência artificial é a capacidade de máqu...
1,O que é um DataFrame no pandas?,Um DataFrame é uma estrutura de dados bidimens...
2,Qual a diferença entre read e readlines em Pyt...,`read()` lê todo o conteúdo do arquivo de uma ...
3,Para que serve um arquivo CSV?,Um arquivo CSV (Comma-Separated Values) armaze...

In [29]:
df_resultado.to_csv("perguntas_e_respostas.csv", index=False, encoding="utf-8")
print("Arquivo final salvo com sucesso.")

Arquivo final salvo com sucesso.

In [30]:
df_final_lido = pd.read_csv("perguntas_e_respostas.csv")
df_final_lido

,pergunta,resposta
0,O que é inteligência artificial?,Inteligência artificial é a capacidade de máqu...
1,O que é um DataFrame no pandas?,Um DataFrame é uma estrutura de dados bidimens...
2,Qual a diferença entre read e readlines em Pyt...,`read()` lê todo o conteúdo do arquivo de uma ...
3,Para que serve um arquivo CSV?,Um arquivo CSV (Comma-Separated Values) armaze...