<a href="https://colab.research.google.com/github/Moquiuti/python-inteligencia-artificial-aplicada/blob/main/DataFrames_e_Filtros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dados_produtos = {
    "Nome do produto": [
        "Notebook Pro", "Mouse Gamer", "Fone Bluetooth", "Cadeira Office",
        "Teclado Mecânico", "Smartphone X", "Livro Python", "Monitor 27",
        "Webcam HD", "Caixa de Som"
    ],
    "Categoria do produto": [
        "eletrônicos", "eletrônicos", "eletrônicos", "móveis",
        "eletrônicos", "eletrônicos", "livros", "eletrônicos",
        "eletrônicos", "eletrônicos"
    ],
    "Preço do produto": [
        4500.00, 180.00, 320.00, 890.00,
        410.00, 2999.00, 79.90, 1200.00,
        250.00, 340.00
    ],
    "Avaliação do produto": [
        4.8, 4.2, 1.8, 3.9,
        4.5, 1.5, 4.9, 2.0,
        1.7, 3.8
    ],
    "Itens vendidos": [
        120, 340, 210, 55,
        180, 98, 500, 75,
        160, 130
    ]
}

df_produtos = pd.DataFrame(dados_produtos)

In [3]:
print("DataFrame completo:")
display(df_produtos)

print("Primeiros registros com head():")
display(df_produtos.head())

DataFrame completo:

,Nome do produto,Categoria do produto,Preço do produto,Avaliação do produto,Itens vendidos
0,Notebook Pro,eletrônicos,4500.0,4.8,120
1,Mouse Gamer,eletrônicos,180.0,4.2,340
2,Fone Bluetooth,eletrônicos,320.0,1.8,210
3,Cadeira Office,móveis,890.0,3.9,55
4,Teclado Mecânico,eletrônicos,410.0,4.5,180
5,Smartphone X,eletrônicos,2999.0,1.5,98
6,Livro Python,livros,79.9,4.9,500
7,Monitor 27,eletrônicos,1200.0,2.0,75
8,Webcam HD,eletrônicos,250.0,1.7,160
9,Caixa de Som,eletrônicos,340.0,3.8,130

Primeiros registros com head():

,Nome do produto,Categoria do produto,Preço do produto,Avaliação do produto,Itens vendidos
0,Notebook Pro,eletrônicos,4500.0,4.8,120
1,Mouse Gamer,eletrônicos,180.0,4.2,340
2,Fone Bluetooth,eletrônicos,320.0,1.8,210
3,Cadeira Office,móveis,890.0,3.9,55
4,Teclado Mecânico,eletrônicos,410.0,4.5,180

In [4]:
categorias = df_produtos["Categoria do produto"]
print("Coluna selecionada:")
display(categorias)

Coluna selecionada:

0    eletrônicos
1    eletrônicos
2    eletrônicos
3         móveis
4    eletrônicos
5    eletrônicos
6         livros
7    eletrônicos
8    eletrônicos
9    eletrônicos
Name: Categoria do produto, dtype: object

In [5]:
valores_unicos = df_produtos["Categoria do produto"].unique()
print("Valores únicos com unique():")
print(valores_unicos)

Valores únicos com unique():
['eletrônicos' 'móveis' 'livros']

In [6]:
valores_unicos_set = set(df_produtos["Categoria do produto"])
print("Valores únicos com set():")
print(valores_unicos_set)

Valores únicos com set():
{'eletrônicos', 'livros', 'móveis'}

In [7]:
produtos_eletronicos = df_produtos[df_produtos["Categoria do produto"] == "eletrônicos"]

print("Produtos da categoria eletrônicos:")
display(produtos_eletronicos)

Produtos da categoria eletrônicos:

,Nome do produto,Categoria do produto,Preço do produto,Avaliação do produto,Itens vendidos
0,Notebook Pro,eletrônicos,4500.0,4.8,120
1,Mouse Gamer,eletrônicos,180.0,4.2,340
2,Fone Bluetooth,eletrônicos,320.0,1.8,210
4,Teclado Mecânico,eletrônicos,410.0,4.5,180
5,Smartphone X,eletrônicos,2999.0,1.5,98
7,Monitor 27,eletrônicos,1200.0,2.0,75
8,Webcam HD,eletrônicos,250.0,1.7,160
9,Caixa de Som,eletrônicos,340.0,3.8,130

In [8]:
produtos_avaliacao_baixa = df_produtos[df_produtos["Avaliação do produto"] < 2.0]

print("Produtos com avaliação menor que 2.0:")
display(produtos_avaliacao_baixa)

Produtos com avaliação menor que 2.0:

,Nome do produto,Categoria do produto,Preço do produto,Avaliação do produto,Itens vendidos
2,Fone Bluetooth,eletrônicos,320.0,1.8,210
5,Smartphone X,eletrônicos,2999.0,1.5,98
8,Webcam HD,eletrônicos,250.0,1.7,160

In [9]:
filtro_combinado = df_produtos[
    (df_produtos["Categoria do produto"] == "eletrônicos") &
    (df_produtos["Preço do produto"] > 300)
]

print("Produtos eletrônicos com preço maior que 300:")
display(filtro_combinado)

Produtos eletrônicos com preço maior que 300:

,Nome do produto,Categoria do produto,Preço do produto,Avaliação do produto,Itens vendidos
0,Notebook Pro,eletrônicos,4500.0,4.8,120
2,Fone Bluetooth,eletrônicos,320.0,1.8,210
4,Teclado Mecânico,eletrônicos,410.0,4.5,180
5,Smartphone X,eletrônicos,2999.0,1.5,98
7,Monitor 27,eletrônicos,1200.0,2.0,75
9,Caixa de Som,eletrônicos,340.0,3.8,130

In [10]:
print("Linha na posição 2 com iloc:")
display(df_produtos.iloc[2])

Linha na posição 2 com iloc:

Nome do produto         Fone Bluetooth
Categoria do produto       eletrônicos
Preço do produto                 320.0
Avaliação do produto               1.8
Itens vendidos                     210
Name: 2, dtype: object

In [11]:
print("Linhas da posição 0 até 4:")
display(df_produtos.iloc[0:5])

Linhas da posição 0 até 4:

,Nome do produto,Categoria do produto,Preço do produto,Avaliação do produto,Itens vendidos
0,Notebook Pro,eletrônicos,4500.0,4.8,120
1,Mouse Gamer,eletrônicos,180.0,4.2,340
2,Fone Bluetooth,eletrônicos,320.0,1.8,210
3,Cadeira Office,móveis,890.0,3.9,55
4,Teclado Mecânico,eletrônicos,410.0,4.5,180

In [12]:
print("Valor específico com iloc [linha 1, coluna 2]:")
print(df_produtos.iloc[1, 2])

Valor específico com iloc [linha 1, coluna 2]:
180.0

In [13]:
df_produtos_com_indice = df_produtos.set_index("Nome do produto")
display(df_produtos_com_indice)

,Categoria do produto,Preço do produto,Avaliação do produto,Itens vendidos
Nome do produto,,,,
Notebook Pro,eletrônicos,4500.0,4.8,120
Mouse Gamer,eletrônicos,180.0,4.2,340
Fone Bluetooth,eletrônicos,320.0,1.8,210
Cadeira Office,móveis,890.0,3.9,55
Teclado Mecânico,eletrônicos,410.0,4.5,180
Smartphone X,eletrônicos,2999.0,1.5,98
Livro Python,livros,79.9,4.9,500
Monitor 27,eletrônicos,1200.0,2.0,75
Webcam HD,eletrônicos,250.0,1.7,160
Caixa de Som,eletrônicos,340.0,3.8,130

In [15]:
print("Registro do produto Notebook Pro:")
display(df_produtos_com_indice.loc["Notebook Pro"])

Registro do produto Notebook Pro:

Categoria do produto    eletrônicos
Preço do produto             4500.0
Avaliação do produto            4.8
Itens vendidos                  120
Name: Notebook Pro, dtype: object

In [16]:
print("Preço do produto Smartphone X:")
print(df_produtos_com_indice.loc["Smartphone X", "Preço do produto"])

Preço do produto Smartphone X:
2999.0

In [17]:
print("Seleção múltipla com loc:")
display(
    df_produtos_com_indice.loc[
        ["Notebook Pro", "Monitor 27"],
        ["Preço do produto", "Itens vendidos"]
    ]
)

Seleção múltipla com loc:

                 Preço do produto  Itens vendidos
Nome do produto
Notebook Pro               4500.0             120
Monitor 27                 1200.0              75

In [18]:
df_produtos_ajustado = df_produtos.copy()

df_produtos_ajustado.loc[
    (df_produtos_ajustado["Categoria do produto"] == "eletrônicos") &
    (df_produtos_ajustado["Avaliação do produto"] < 2.0),
    "Categoria do produto"
] = "eletrônicos - revisão"

display(df_produtos_ajustado)

,Nome do produto,Categoria do produto,Preço do produto,Avaliação do produto,Itens vendidos
0,Notebook Pro,eletrônicos,4500.0,4.8,120
1,Mouse Gamer,eletrônicos,180.0,4.2,340
2,Fone Bluetooth,eletrônicos - revisão,320.0,1.8,210
3,Cadeira Office,móveis,890.0,3.9,55
4,Teclado Mecânico,eletrônicos,410.0,4.5,180
5,Smartphone X,eletrônicos - revisão,2999.0,1.5,98
6,Livro Python,livros,79.9,4.9,500
7,Monitor 27,eletrônicos,1200.0,2.0,75
8,Webcam HD,eletrônicos - revisão,250.0,1.7,160
9,Caixa de Som,eletrônicos,340.0,3.8,130

In [20]:
df_csv = pd.read_csv("meu_csv.csv")
display(df_csv)

       nome  media
0       Ana    7.5
1    Carlos    8.2
2   Beatriz    9.1
3     Diogo    6.8
4   Eduarda    5.9
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

In [21]:
display(df_csv.head())

      nome  media
0      Ana    7.5
1   Carlos    8.2
2  Beatriz    9.1
3    Diogo    6.8
4  Eduarda    5.9

In [22]:
import os
from google.colab import userdata
from google import genai

In [24]:
os.environ["GOOGLE_API_KEY"] = userdata.get("python-ai-integrada")
client = genai.Client()

In [25]:
df_reviews = pd.read_csv("reviews.csv")
display(df_reviews.head())

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [26]:
print(df_reviews.columns)

Index(['reviewerID', 'asin', 'reviewerName', 'reviewText', 'unixReviewTime',
       'reviewTime', 'day_diff', 'helpful_yes', 'total_vote'],
      dtype='object')

In [33]:
import time

def classificar_sentimento(review):
    prompt = f"""
Você é um classificador de sentimentos.

Classifique a resenha abaixo retornando apenas uma destas opções:
Positiva
Negativa
Neutra

Exemplos:
Resenha: "Produto excelente, superou minhas expectativas."
Classificação: Positiva

Resenha: "Não gostei, veio com defeito e parou de funcionar."
Classificação: Negativa

Resenha: "O produto é ok, nada demais."
Classificação: Neutra

Agora classifique:
Resenha: "{review}"
Classificação:
"""

    for tentativa in range(3):
        try:
            resposta = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt
            )

            resultado = resposta.text.strip()

            if "Positiva" in resultado:
                return "Positiva"
            elif "Negativa" in resultado:
                return "Negativa"
            elif "Neutra" in resultado:
                return "Neutra"
            else:
                return "Neutra"

        except Exception as e:
            print(f"Tentativa {tentativa + 1} falhou: {e}")
            time.sleep(2)

    return "Neutra"

In [32]:
lista_de_analises_de_sentimentos = []

for review in df_reviews["reviewText"]:
    sentimento = classificar_sentimento(review)
    lista_de_analises_de_sentimentos.append(sentimento)

Erro ao analisar review: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
Erro ao analisar review: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
Erro ao analisar review: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 59.411904236s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '59s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 59.16050863s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '59s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 56.067085065s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '56s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 55.715205632s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '55s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 55.467245164s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '55s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 55.142508646s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '55s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 52.231333762s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '52s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 51.982078889s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '51s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 51.707481696s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '51s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 51.437757055s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '51s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 51.159721848s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '51s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 50.899065389s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '50s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 50.586979452s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '50s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 50.327505063s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '50s'}]}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 50.052773739s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '50s'}]}}
Erro ao analisar review: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
Erro ao analisar review: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 48.243104307s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '48s'}]}}
Erro ao analisar review: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
Erro ao analisar review: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
Erro ao analisar review: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

In [34]:
df_reviews["Análises de Sentimentos"] = lista_de_analises_de_sentimentos
display(df_reviews.head())

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,Análises de Sentimentos
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,Neutra
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Neutra
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,Positiva
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,Positiva
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,Positiva

In [35]:
df_reviews.to_csv("reviews_com_sentimento.csv", index=False, encoding="utf-8")
print("Arquivo reviews_com_sentimento.csv salvo com sucesso.")

Arquivo reviews_com_sentimento.csv salvo com sucesso.